/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface SkeletonLoader {
    'animated': boolean;
    'borderRadius': string;
    'color': string;
    'count': number;
    'height': string;
    'heightRandomness': number;
    'width': string;
    'widthRandomness': number;
  }
}

declare namespace LocalJSX {
  interface SkeletonLoader extends JSXBase.HTMLAttributes {
    'animated'?: boolean;
    'borderRadius'?: string;
    'color'?: string;
    'count'?: number;
    'height'?: string;
    'heightRandomness'?: number;
    'width'?: string;
    'widthRandomness'?: number;
  }

  interface ElementInterfaces {
    'SkeletonLoader': Components.SkeletonLoader;
  }

  interface IntrinsicElements {
    'SkeletonLoader': LocalJSX.SkeletonLoader;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {


  interface HTMLSkeletonLoaderElement extends Components.SkeletonLoader, HTMLStencilElement {}
  var HTMLSkeletonLoaderElement: {
    prototype: HTMLSkeletonLoaderElement;
    new (): HTMLSkeletonLoaderElement;
  };
  interface HTMLElementTagNameMap {
    'skeleton-loader': HTMLSkeletonLoaderElement
  }

  interface ElementTagNameMap {
    'skeleton-loader': HTMLSkeletonLoaderElement;
  }
}

